Added the ability to search for units without specific abilities
piotrberlowski/mul-search pull request #13
Opened 2024-02-27 12:22 UTC by Hwatwasthat

I've just added the option to put a ! before an ability in the abilities search box to search for units without a specific ability. helpful to just cut out things like C3 and mhq that add points but might not be needed. Something I wanted and I figured others might want too!

2024-02-27 13:54 UTC, piotrberlowski requested changes
Many thanks for your contribution. I left a suggestion on how to change it a bit (but I typed the code here in the browser so it might not even compile). Please take a look and see what you think.

Also, a vercel deployment may have been created for this PR so you should be able to test it in a staging env.

I'll approve and merge as soon as you share your thoughts.

2024-02-27 13:54 UTC, piotrberlowski commented on src/app/(builder)/builder/filteredTable.tsx
> +    }).every((match) => match === true);
```suggestion
    const matches = queries.reduce((res, query) => {
        query = query.toLowerCase().trim();
        const cleanQ = query.replace(/^!/, '');
        const neg = q != cleanQ
        const contains = abilities?.toLowerCase().includes(cleanQ);
        return res && (neg ^ contains);
    }, true);
```
I think this is a bit cleaner this way? Also, appreciate the fix to the reduce bug - I forgot to _actually reduce_ the value. I knew the bug was there, but just didn't get around to fixing it.

2024-02-27 15:00 UTC, Hwatwasthat commented
Should work all nicely. Tested it locally and seems to filter properly :).

2024-02-28 00:08 UTC, piotrberlowski approved these changes

2024-02-28 00:08 UTC, merged